<?php

/**
 * @file
 *
 * Lesser Forms - don't bother content managers with settings they don't need.
 */

/**
 * Implements hook_form_alter().
 */
function lesser_forms_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id) {
  $user = \Drupal::currentUser();

  // @FIXME
// Could not extract the default value because it is either indeterminate, or
// not scalar. You'll need to provide a default value in
// config/install/lesser_forms.settings.yml and config/schema/lesser_forms.schema.yml.
$settings = \Drupal::config('lesser_forms.settings')->get('lesser_forms_config');
  $user_roles = isset($settings['applies_to']) ? $settings['applies_to'] : array();

  if (array_intersect(array_keys(array_filter($user_roles)), $user->roles)) {

    if (isset($settings['promote']) && $settings['promote']) {
      $form['options']['promote']['#access'] = FALSE;
    }
    if (isset($settings['sticky']) && $settings['sticky']) {
      $form['options']['sticky']['#access'] = FALSE;
    }
    if (isset($settings['preview']) && $settings['preview']) {
      $form['actions']['preview']['#access'] = FALSE;
    }
    if (isset($settings['author']) && $settings['author']) {
      $form['author']['#access'] = FALSE;
    }
    if (isset($settings['revision_information']) && $settings['revision_information']) {
      $form['revision_information']['#access'] = FALSE;
    }

    // Pathauto will hook after the build, so we need this line.
    if (isset($settings['pathauto']) && $settings['pathauto']) {
      $form['#after_build'][] = 'lesser_forms_form_after_build';
    }
  }
}

/**
 * Custom after build.
 *
 * @param array $form
 *   Form.
 * @param array $form_state
 *   Form state.
 *
 * @return array
 *   Returns the form array.
 */
function lesser_forms_form_after_build(array $form, array &$form_state) {
  $form['path']['#access'] = FALSE;
  return ($form);
}

/**
 * @FIXME
 * This implementation of hook_menu() cannot be automatically converted because
 * it contains logic (i.e., branching statements, function calls, object
 * instantiation, etc.) You will need to convert it manually. Sorry!
 * 
 * For more information on how to convert hook_menu() to Drupal 8's new routing
 * and linking systems, see https://api.drupal.org/api/drupal/core%21includes%21menu.inc/group/menu/8
 */
function lesser_forms_menu() {
  $items['admin/config/content/lesser_forms'] = array(
    'title' => 'Lesser Forms',
    'description' => 'Configure Lesser forms settings.',
    'page callback' => 'drupal_get_form',
    'type' => MENU_NORMAL_ITEM,
    'page arguments' => array('lesser_forms_configuration_form'),
    'access arguments' => array('administer lesser forms'),
    'file' => 'admin/lesser_forms.admin.inc',
    'file path' => drupal_get_path('module', 'lesser_forms'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function lesser_forms_permission() {
  return array(
    'administer lesser forms' => array(
      'title' => t('Administer Lesser Forms'),
      'description' => t('Perform administration tasks for Lesser Forms UI.'),
    ),
  );
}
