<?php

/**
 * @file
 *
 * Lesser Forms - don't bother content managers with settings they don't need.
 */

/**
 * Implements hook_form_alter().
 */
function lesser_forms_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id) {
  $user = \Drupal::currentUser();
  $settings = \Drupal::config('lesser_forms.settings')
    ->get('lesser_forms_config');

  if ($settings == NULL) {
    return;
  }

  if (array_intersect(array_keys(array_filter($settings['applies_to'])), $user->roles)) {
    if (isset($settings['promote']) && $settings['promote']) {
      $form['promote']['#access'] = FALSE;
    }
    if (isset($settings['sticky']) && $settings['sticky']) {
      $form['sticky']['#access'] = FALSE;
    }
    if (isset($settings['preview']) && $settings['preview']) {
      $form['preview']['#access'] = FALSE;
    }
    if (isset($settings['author']) && $settings['author']) {
      $form['author']['#access'] = FALSE;
    }
    if (isset($settings['revision_information']) && $settings['revision_information']) {
      $form['revision_information']['#access'] = FALSE;
    }

    // Pathauto will hook after the build, so we need this line.
    if (isset($settings['pathauto']) && $settings['pathauto']) {
      $form['#after_build'][] = 'lesser_forms_form_after_build';
    }
  }
}

/**
 * Custom after build.
 *
 * @param array $form
 *   Form.
 * @param array $form_state
 *   Form state.
 *
 * @return array
 *   Returns the form array.
 */
function lesser_forms_form_after_build(array $form, &$form_state) {
  $form['path']['#access'] = FALSE;
  return ($form);
}